version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db_postgres_ic4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    image: redis:latest
    container_name: db_redis_ic4
    ports:
      - "6379:6379"